#!/bin/sh

set -e

usage ()
{
	echo "usage: $(basename $0) HOST" >&2
	echo "" >&2
	echo "  where:" >&2
	echo "    HOST is the IP or hostname address of the board to test" >&2
	echo "" >&2
	echo "The board should be running netserver, the sever-side of netperf" >&2
	exit 1
}

[ $# == 1 ] || usage

echo "UDP/IP Performance test"

exec netperf -t UDP_STREAM -H "$1" -4 -c -C -- -m 1472
